### ISSUE TITLE
Edge Filtering

### ISSUE THREAD

**Issue by jwertheim** [veg/hivtrace#3]
Encountered this error multiple times with different sequence ids raising the flag:
```
Traceback (most recent call last):
  File "/usr/local/bin/hivnetworkcsv", line 70, in <module>
    make_hiv_network () 
  File "/usr/local/bin/hivnetworkcsv", line 12, in make_hiv_network
    network = build_a_network()
  File "/usr/local/bin/networkbuild.py", line 447, in build_a_network
    edge_stats = network.test_edge_support (os.path.abspath (run_settings.sequences), *network.find_all_triangles(network.reduce_edge_set()))
  File "/opt/hivtrace/env/lib/python3.2/site-packages/hivclustering-0.2-py3.2.egg/hivclustering/mtnetwork.py", line 2005, in test_edge_support
    processed_objects = pool.map(evaluator, blocked)
  File "/opt/python-3.2.3/lib/python3.2/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/opt/python-3.2.3/lib/python3.2/multiprocessing/pool.py", line 556, in get
    raise self._value
RuntimeError: Failed to map SEQUENCE_ID_HERE in call to assert(
```

**Comment by spond** [comment]
Hi Joel,

That's a hyphy script error. Can you give Steven the files that trigger it? I have not seen it before. Are you including LANL sequences in the analysis?

Sergei

**Comment by jwertheim** [comment]
It's all NYC sequences. I'll work with Steven on it and send him the path to the files.

Thanks,
Joel

Sent from my iPhone

On Aug 12, 2015, at 8:18 PM, Sergei Pond <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Joel,

That's a hyphy script error. Can you give Steven the files that trigger it? I have not seen it before. Are you including LANL sequences in the analysis?

Sergei

**Comment by stevenweaver** [comment]
Hi Joel, 

This issue occurs when the source fasta file supplied is not the same that was used to generate the distance file. Specifically, if there is a referenced sequence id in the distance file that is not in the source fasta file, this error will be thrown.

**Comment by spond** [comment]
Hi Steven,

Can we add a more informative error message? 

Thanks,
Sergei

**Comment by stevenweaver** [comment]
Sure. I will do that now.
