### ISSUE TITLE
-c option returns error

### ISSUE THREAD

**Issue by Chjulian** [veg/hivtrace#43]
Hi all,

Hivtrace runs ok in a MacOS 10.13.5 (Python 3.6.5) with:

`hivtrace -i data.fas -a average -r HXB2_prrt -t 0.0015 -m 500 -g .05`

But when I add "-c"

`hivtrace -i data.fas -a average -r HXB2_prrt -t 0.0015 -m 500 -g .05 -c`

I get:

> Traceback (most recent call last):
  File "/usr/local/bin/hivtrace", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 809, in main
    attributes_file=ATTRIBUTES_FILE)
  File "/usr/local/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 706, in hivtrace
    complete_stderr)
subprocess.CalledProcessError: <exception str() failed>

Any ideas? Cheers

**Comment by stevenweaver** [comment]
Dear @Chjulian, 

I will review this issue shortly. It might take until tomorrow morning, ET. 

Best,
Steven

**Comment by stevenweaver** [comment]
I was able to reproduce this bug. I will update the issue once it is resolved in the next release.
