### ISSUE TITLE
Output clarifications

### ISSUE THREAD

**Issue by Chjulian** [veg/hivtrace#44]
Hi Guys,

I have a pair of questions:

1. why the "Genetic distance Mean [Median, IQR]" for some clusters is "NaN [NaN, NaN - NaN]"

2. I was expecting all clusters to have links connecting their respective nodes but this is rarely the case. I only got one cluster with a link on it:

<img width="393" alt="screen shot 2018-06-27 at 16 38 28" src="https://user-images.githubusercontent.com/7526558/41984780-6e60c9e8-7a29-11e8-87c1-797524013c8f.png">

If this related to a different threshold than the one specified by -t/--threshold? 

Ponds et al. (2018) mention a user specified threshold D = 0.0015 to draw links between individuals but the --help does not list any other threshold.

3. I got 21 cluster with two individuals, one cluster with three individuals and the cluster displayed above. As I mentioned, there are not links in any other cluster but cluster 16.

However, the output says:
Links/node:
Mean: 1.4
Median: 1.0

So where are these links, not being displayed?

4. Could you please explain the "Genetic distances (links only)" field?

For example, it says Mean 0.236%, but I do not get the meaning of this percentage.

Also, I'd like two minor clarifications concerning the execution:

5. hivtrace still requires the argument -g/--fraction with -a/--ambiguities average but I assume it is not used, right?

6. If my sequences are aligned then I should just add the option --skip-alignment, right?

Cheers,

Julian

**Comment by Chjulian** [comment]
7. I also noted nodes size 2 with 1.5 links [1.5, 1.3 - 1.8] and genetic distance IQRs [0.00033, 0.00017 - 0.00050]. I was expecting to have more than 1 link and IQRs only for nodes size > 2. Am I missing something? :)

BW

Julian

**Comment by stevenweaver** [comment]
Dear Julian, 

This a known issue. `hivclusteringcsv` was updated recently in order to ensure consistent sorted output, unfortunately that commit, has caused a problem with the visualization. 

I have PR associated with the bug here that I have just merged and released:
https://github.com/veg/hivtrace/pull/42

You can either choose one of two commands and rerun HIV-TRACE.

`pip install -U hivtrace`

OR

`pip install hivclustering==1.2.8`

Apologies for this inconvenience! Allow me some time to answer the rest of the questions.

Best,
Steven

**Comment by Chjulian** [comment]
Hi Steven, great, thanks! and sorry for asking so many questions.

BW,

Julian

**Comment by stevenweaver** [comment]
Dear Julian, 

> 4. Could you please explain the "Genetic distances (links only)" field?

Each edge in a cluster has an associated `length`. `length` in HIV-TRACE is the genetic distance calculated by [tn93](https://github.com/veg/tn93). Ultimately, it is the estimated percentage of nucleotide substitutions between two genetic sequences. The field describes the mean of the distances between nodes in the cluster (thus explaining how tightly linked the cluster is). A mean of .236 (if that is what is being directly reported) is extraordinarily high. We usually place the threshold around 1.5% (0.015) for clustering. Please see [Wertheim et. al. 2017](http://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1006000) for a very nice explanation of why. 


The code itself is straightforward. 

```
    self.edges.forEach(function(e, i) { 
      self.clusters[
        self.cluster_mapping[self.nodes[e.target].cluster]
      ].distances.push(e.length);
    });  

    self.clusters.forEach(function(d, i) { 
      d.distances = helpers.describe_vector(d.distances);
    }); 

```

`helpers.describe_vector` simply calculates the summary statistics.


> 5. hivtrace still requires the argument -g/--fraction with -a/--ambiguities average but I assume it is not used, right?

That is true. Thank you for bringing this to our attention. I will flesh out the `help` descriptions within the script as well.

> 6. If my sequences are aligned then I should just add the option --skip-alignment, right?
Yes, as long as you are not using the `-c` parameter. 

> 7. I also noted nodes size 2 with 1.5 links [1.5, 1.3 - 1.8] and genetic distance IQRs [0.00033, 0.00017 - 0.00050]. I was expecting to have more than 1 link and IQRs only for nodes size > 2. Am I missing something? :)

That is definitely odd. I will see if I can reproduce this.
