### ISSUE TITLE
can not install hivtrace using command line : "pip3 install hivtrace"

### ISSUE THREAD

**Issue by lixingguang** [veg/hivtrace#50]
libexec/gcc/x86_64-apple-darwin17.5.0/8.1.0/cc1
      Reason: image not found
    gcc: internal compiler error: Abort trap: 6 signal terminated program cc1
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <https://gcc.gnu.org/bugs/> for instructions.
    error: command 'gcc' failed with exit status 4
    
    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/q4/gvrdsnj94vl527nfhj25rxh40000gn/T/pip-install-fj234sxj/pysam/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/q4/gvrdsnj94vl527nfhj25rxh40000gn/T/pip-record-k_n9iuce/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/q4/gvrdsnj94vl527nfhj25rxh40000gn/T/pip-install-fj234sxj/pysam/

**Comment by stevenweaver** [comment]
Dear @lixingguang, 

Apologies for the delay. Can you please try installing `pysam` independently and see if the issue persists?

Best,
Steven

**Comment by lixingguang** [comment]
@stevenweaver can not install pysam, still have error.

**Comment by stevenweaver** [comment]
@lixingguang, 

pysam is a dependency of hivtrace, and it looks like there is either some sort of path issue, permissions issue, or compiler issue associated with your environment. I cannot replicate it with ours.

The people over at https://github.com/pysam-developers/pysam/issues might be able to provide better assistance. 

Best,
Steven

**Comment by lixingguang** [comment]
lixingguangtekiMacBook-puro:~ lixingguang$ pip3 install hivtrace
Requirement already satisfied: hivtrace in /anaconda3/lib/python3.6/site-packages (0.1.6)
Requirement already satisfied: biopython>=1.58 in /anaconda3/lib/python3.6/site-packages (from hivtrace) (1.72)
Collecting BioExt>=0.17.2 (from hivtrace)
  Downloading https://files.pythonhosted.org/packages/c4/f0/779ed11ff3ce38d9a317a7988ec607202e8124d57e01b3f9b2d566860720/bioext-0.19.5.tar.gz (1.8MB)
    100% |████████████████████████████████| 1.8MB 28kB/s 
Collecting HyPhy>=0.1.1 (from hivtrace)
  Could not find a version that satisfies the requirement HyPhy>=0.1.1 (from hivtrace) (from versions: )
No matching distribution found for HyPhy>=0.1.1 (from hivtrace)

**Comment by lixingguang** [comment]
@stevenweaver why hivtrace can not include hyphy?
