### ISSUE TITLE
HIV-TRACE on UGE

### ISSUE THREAD

**Issue by mdhall272** [veg/hivtrace#63]
I'm aware this is probably a difficult issue to track down if nobody has encountered it, but I wondered if anyone has - I'm trying to run HIV-TRACE in a job script on the Univa Grid Engine, but the jobs just die silently. There is nothing to standard output or standard error to determine what went wrong; those files are empty. I do not _think_ it has run out of RAM (which I've often found to be the culprit when jobs silently die) because I have given it a lot; more than I have on my laptop where it runs successfully. The only clue is hivtrace.log, which I have attached.

Any ideas?

[hivtrace.log](https://github.com/veg/hivtrace/files/3798537/hivtrace.log)

**Comment by stevenweaver** [comment]
Dear @mdhall272, 

Before investigating further, may I inquire whether this happens only when multiple hivtrace jobs are running at the same time? Or does it happen with a single job run as well?

Best,
Steven

**Comment by mdhall272** [comment]
No - it happens regardless. I've never got it to work as a cluster job. The script does work on a login node.

**Comment by stevenweaver** [comment]
Unfortunately, the log only lets me know that the it is failing at the alignment step. 

Three possible issues I would investigate that could cause this is 

1) the architecture of the compute node on which this is running is different from the login node. For example, the login node having `avx2` support and the compute node not having such support. 

2) the environment is different on the compute node than the login node (a different version of libc could cause the problem, for example). 

3) A limit of some sort is being tripped. If it is not memory, it could potentially be default walltime. 

The administrator might have access to syslogs that could help find the source of the problem. 

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @mdhall272, 

I'm going to close this issue, but please feel free to reopen if you are facing continued obstacles on your cluster.

Best,
Steven
