### ISSUE TITLE
Error during tn93 steps

### ISSUE THREAD

**Issue by lexleong** [veg/hivtrace#65]
Hi veg,

I have installed the hivtrace onto my computer without any issue. However, when I tried running it against one of my fasta sequences, it came back with an error during the tn93 steps (refer `below).`
`$ hivtrace -i ./1932701285MUAL.fasta -a resolve -r HXB2_prrt -t .015 -m 500 -g .05 -c
Traceback (most recent call last):
  File "/home/iidlleo/.local/bin/hivtrace", line 10, in <module>
    sys.exit(main())
  File "/home/iidlleo/.local/lib/python3.7/site-packages/hivtrace/hivtrace.py", line 840, in main
    attributes_file=ATTRIBUTES_FILE)
  File "/home/iidlleo/.local/lib/python3.7/site-packages/hivtrace/hivtrace.py", line 561, in hivtrace
    raise Exception(' '.join(tn93_process) + "returned empty file")
Exception: tn93 -q -o /tmp/hivtrace-dks3vvkf/1932701285MUAL.fasta_user.tn93output.csv -t .015 -a resolve -l 500 -g .05 -f csv ./1932701285MUAL.fasta_output.fastareturned empty file`

It looks like it has to do with some empty file that is not looking right. I wonder if anyone can help me out?

Cheers,
Lex

**Comment by stevenweaver** [comment]
Dear @lexleong, 

Have you installed tn93 on your machine? Unfortunately, tn93 must be installed separately. Instructions can be found in the [README](https://github.com/veg/tn93).

Please let me know if that was the issue.

Best,
Steven

**Comment by lexleong** [comment]
Hi @stevenweaver,

I have downloaded tn93 to my server before running the hivtrace. 

But, I figured out this problem has plenty to do with my naivety/stupidness in HIV analysis. In my fasta file, there were only 1 unaligned sequence. After testing the program with several aligned sequences, HIV-trace ran without any error! 

Sorry, I jumped too quicky...
Cheers,
Lex
