### ISSUE TITLE
Sequence length error

### ISSUE THREAD

**Issue by noranekonobokkusu** [veg/hivtrace#70]
Hi,

When I'm adding the '-c' option, the program crashes. The end of the log file looks like this:

<pre>
INFO:root:{"type": "status update", "index": 4, "title": "Inferring, filtering, and analyzing molecular transmission network", "status": 3, "msg": "Marked 13 nodes as being in the contaminant clusters\nRunning edge filtering on 1 clusters with 3 or more edges\n\nFiltering a set of 47374 edges (1/1 clusters)                                                                                 \nFiltering a set of 47374 edges (1/1 clusters). Pass 0, 32768 triangles, 100 filtered edges\nFiltering a set of 47274 edges (1/1 clusters). Pass 1, 65536 triangles, 35 filtered edges\nFiltering a set of 47239 edges (1/1 clusters). Pass 2, 98304 triangles, 6 filtered edges\nFiltering a set of 47233 edges (1/1 clusters). Pass 3, 131072 triangles, 21 filtered edges\nFiltering a set of 47212 edges (1/1 clusters). Pass 4, 163840 triangles, 4 filtered edges\nFiltering a set of 47208 edges (1/1 clusters). Pass 5, 196608 triangles, 16 filtered edges\nFiltering a set of 47192 edges (1/1 clusters). Pass 6, 229376 triangles, 23 filtered edges\nFiltering a set of 47169 edges (1/1 clusters). Pass 7, 262144 triangles, 3 filtered edges\nEdge filtering identified 208 edges for removal\nFitting the degree distribution to various densities\n"}
INFO:root:{"type": "status update", "index": 5, "title": "Computing pairwise TN93 distances against a public database", "status": 2, "msg": ""}
DEBUG:root:/home/noraneko/tn93/tn93 -q -o /tmp/hivtrace-xg4yr4xv/data.fasta_usertolanl.tn93output.csv -t 0.05 -a resolve -f csv -g 0.03 -l 100 -s /mnt/lustre/noraneko/.local/lib/python3.7/site-packages/hivtrace/rsrc/LANL.FASTA data.fasta_output.fasta
</pre>

Error log says:

<pre>
All sequences must have the same length (2844), but sequence 'B|US|M17449|1984' had length 1617Traceback (most recent call last):
  File "/home/noraneko/.local/bin/hivtrace", line 11, in <module>
    load_entry_point('hivtrace==0.5.2', 'console_scripts', 'hivtrace')()
  File "/home/noraneko/.local/lib/python3.7/site-packages/hivtrace/hivtrace.py", line 853, in main
    prior=PRIOR
  File "/home/noraneko/.local/lib/python3.7/site-packages/hivtrace/hivtrace.py", line 670, in hivtrace
    subprocess.check_call(lanl_tn93_process, stdout=DEVNULL)
  File "/home/tools/python/Python-3.7.4/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/noraneko/tn93/tn93', '-q', '-o', '/tmp/hivtrace-xg4yr4xv/data.fasta_usertolanl.tn93output.csv', '-t', '0.05', '-a', 'resolve', '-f', 'csv', '-g', '0.03', '-l', '100', '-s', '/mnt/lustre/noraneko/.local/lib/python3.7/site-packages/hivtrace/rsrc/LANL.FASTA', 'data.fasta_output.fasta']' returned non-zero exit status 1.
</pre>

Am I doing something wrong?

Thanks!

**Comment by stevenweaver** [comment]
Dear @noranekonobokkusu, 

The `-c` option performs pairwise distance calculations between your dataset and a pre-aligned LANL dataset. The pre-aligned LANL dataset contains sequences in the [pro/rt region](https://www.hiv.lanl.gov/content/sequence/HIV/MAP/landmark.html), namely 2253 - 3870. 

This region has limited length variation (unlike, say, env) across all major HIV-1 subtypes, and the rarity of insertions and deletions permits robust pairwise alignment to a reference sequence.

If you wish to use a different region, then you cannot use the built-in LANL dataset for comparison, and will have to perform the analysis separately.

Best,
Steven

**Comment by noranekonobokkusu** [comment]
Dear @stevenweaver,

Thanks for your reply!
I am using a ~1,000 bases piece of the pro/rt region. 'B|US|M17449|1984' sounds like a sequence from the LANL dataset (I don't have the US samples) and the error above mentions that something is wrong with this particular sequence. I don't understand how this is related to my dataset. Does it indicate somehow that something is wrong with my dataset?

Best,
Ksenia

**Comment by stevenweaver** [comment]
Dear @noranekonobokkusu, 

It doesn't indicate anything is wrong with your dataset. It sounds like you might want to omit the `-c` flag altogether, since that performs analysis with a pre-computed US dataset for a very specific use-case. 

Best,
Steven
