### ISSUE TITLE
Unable to run hivtrace: returned non-zero exit status 1

### ISSUE THREAD

**Issue by Xiecenyao** [veg/hivtrace#73]
I run hivtrace and get the following error:
`hivtrace -i total.fasta -a resolve -r HXB2_prrt -t .2 -m 500 -g 0.2
Traceback (most recent call last):
  File "/usr/local/bin/bealign", line 14, in <module>
    from BioExt.io import BamIO
  File "/usr/local/lib64/python3.6/site-packages/BioExt/io/BamIO/__init__.py", line 7, in <module>
    from BioExt.io import _SamBamIO
  File "/usr/local/lib64/python3.6/site-packages/BioExt/io/_SamBamIO.py", line 8, in <module>
    from Bio.Alphabet import single_letter_alphabet
  File "/usr/local/lib64/python3.6/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
Traceback (most recent call last):
  File "/usr/local/bin/hivtrace", line 11, in <module>
    load_entry_point('hivtrace==0.6.2', 'console_scripts', 'hivtrace')()
  File "/usr/local/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 807, in main
    prior=PRIOR
  File "/usr/local/lib/python3.6/site-packages/hivtrace/hivtrace.py", line 438, in hivtrace
    subprocess.check_call(bealign_process, stdout=DEVNULL)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bealign', '-q', '-r', 'HXB2_prrt', '-m', 'HIV_BETWEEN_F', '-R', 'total.fasta', '/tmp/hivtrace-8u2ukzl5/total.fasta_output.bam']' returned non-zero exit status 1.`

**Comment by stevenweaver** [comment]
Dear @Xiecenyao, 

Would you mind providing the contents of `pip freeze`? I'm curious to see which versions of `BioExt`, `hivtrace`, and `biopython` you are using. 

Best,
Steven

**Comment by mlarjim** [comment]
Hi! I get exactly the same error. pip freeze, biopython is v1.78:
attrs==20.3.0
bio==0.3.0
bioext==0.19.8
biopython @ file:///home/conda/feedstock_root/build_artifacts/biopython_1610629021051/work
biopython-extensions==0.18.6
certifi==2020.12.5
chardet==4.0.0
ConsensusCore==1.0.2
Cython @ file:///home/conda/feedstock_root/build_artifacts/cython_1610095929146/work
fakemp==0.9.1
hivclustering==1.6.3
hivtrace==0.6.2
hppy==0.9.9
hyphy-python==0.1.10
idna==2.10
importlib-metadata==3.4.0
iniconfig==1.1.1
joblib==1.0.1
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1610324545699/work
packaging==20.9
pluggy==0.13.1
py==1.10.0
pyparsing==2.4.7
pysam==0.16.0.1
pytest==6.2.2
requests==2.25.1
scipy==1.5.4
six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
toml==0.10.2
tornado==6.1
typing-extensions==3.7.4.3
urllib3==1.26.3
zipp==3.4.0

**Comment by stevenweaver** [comment]
Dear @mlarjim, 

Can you please remove `biopython-extensions` and try again?

```
pip uninstall biopython-extensions
```

Best,
Steven

**Comment by mlarjim** [comment]
Thank you for your answer, Steven. However,  now I get:
`FileNotFoundError: [Errno 2] No such file or directory: 'bealign'`
