### ISSUE TITLE
Characteristics of attributes file

### ISSUE THREAD

**Issue by mlarjim** [veg/hivtrace#75]
Hi,
I want to add attributes such as location to my nodes but I don't know how to make the attributes file. Does it need to be a .csv or a .json file?

**Comment by stevenweaver** [comment]
Dear @mlarjim, 

May I direct you to this [issue](https://github.com/veg/hivtrace-viz/issues/72) for examples of what the schema and attributes file look like?

The point of interest is the `-a` argument example for the `hivannotate` command (but is the same format as `--atributes-file` for `hivtrace`, which is
```
[
  {
    "cur_city_name": "Los Angeles",
    "cur_state_cd": "California",
    "hiv_aids_dx_dt": "2008-05-29T07:00:00.000Z",
    "vl_recent_value": "71341",
    "vital_status": "Missing",
    "ehars_uid": "GA00HHARS001056*",
    "rsd_state_cd": "California",
    "race": "Hispanic/Latino",
    "trans_categ": "Missing"
  },
  {
    "cur_city_name": "Los Angeles",
    "cur_state_cd": "California",
    "hiv_aids_dx_dt": "2008-08-08T07:00:00.000Z",
    "vl_recent_value": "0",
    "vital_status": "Missing",
    "ehars_uid": "GA00HHARS005262*",
    "rsd_state_cd": "California",
    "race": "White",
    "trans_categ": "Heterosexual Contact-Female"
  }
]
```
Best,
Steven

**Comment by mlarjim** [comment]
Thank you, dear Steven!

**Comment by anaabecasis** [comment]
Hi,
I'm wondering whether we can use the csv format for the attributes. If yes, which format should it follow specifically?
We are trying to load the attributes in a csv file but it doesn't work. The format you specify above will require a lot of work...
is there way to convert the csv file to the format you specify above?
thank you
Ana Abecasis
