### ISSUE TITLE
Problems visualising the json output on https://veg.github.io/hivtrace-viz/

### ISSUE THREAD

**Issue by dredre86** [veg/hivtrace#76]
So we have run the fasta file using HIV trace and the output was generated without any errors. We then tried to visualize the json file at https://veg.github.io/hivtrace-viz/ but the link to 'File' to upload the output does not lead anywhere.

Are we doing something wrong on the page? We have also tried running it from the terminal but it would not load the json file.

**Comment by noranekonobokkusu** [comment]
I'm having same issues!

**Comment by stevenweaver** [comment]
Dear @dredre86 and @noranekonobokkusu, 

Apologies for the delay. The issue should now be resolved. 

Best,
Steven
