### ISSUE TITLE
Unable to intall HIVTRACE

### ISSUE THREAD

**Issue by Huanchang-Yan** [veg/hivtrace#79]
Hello! I have follow the instruction for HIVTRACE and have installed System Dependencies sucessfully. However, when I tried to install HIVTRACE and the error log says:

    /usr/bin/ld: cannot find -lssl
    /usr/bin/ld: cannot find -lcrypto
    /usr/bin/ld: cannot find -lcurl
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-g++' failed with exit status 1

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6dscu327/hyphy-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3cczxch_-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-6dscu327/hyphy-python/

And my content of pip3 freeze is: 
asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
bioext==0.20.1
biopython==1.79
blinker==1.4
certifi==2018.1.18
chardet==3.0.4
click==6.7
cloud-init==20.2
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
Cython==0.29.24
distro-info===0.18ubuntu0.18.04.1
fakemp==0.9.1
httplib2==0.9.2
hyperlink==17.3.1
idna==2.6
incremental==16.10.1
Jinja2==2.10
joblib==1.0.1
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
MarkupSafe==1.0
netifaces==0.10.4
numpy==1.19.5
oauthlib==2.0.6
PAM==0.4.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycrypto==2.6.1
pygobject==3.26.1
PyJWT==1.5.3
pyOpenSSL==17.5.0
pysam==0.16.0.1
pyserial==3.4
python-apt==1.6.5+ubuntu0.3
python-debian==0.1.32
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
requests-unixsocket==0.1.5
scipy==1.5.4
SecretStorage==2.3.1
service-identity==16.0.0
six==1.16.0
ssh-import-id==5.7
systemd-python==234
Twisted==17.9.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.22
zope.interface==4.3.2

**Comment by stevenweaver** [comment]
Dear @Huanchang-Yan, 

You need to install libcurl in order to successfully install hivtrace. 
`libcurl4-openssl-dev` on Ubuntu. 

Best,
Steven

**Comment by Huanchang-Yan** [comment]
Dear @stevenweaver ,

Thanks for your help.
I have installed libcurl4-openssl-dev, libssl-dev, and openssl and it worked well. 

Best wishes,
Huanchang
