### ISSUE TITLE
HIV-Trace gets stuck when exporting JSON result file

### ISSUE THREAD

**Issue by denisbeslic** [veg/hivtrace#81]
Dear authors,

I'm trying to use HIVTRACE to analyze transmission clusters in SARS-CoV-2 data, which was aligned using MAFFT.
I ran the following command:
```
hivtrace -i SARS-Cov-10K-ALIGNED.fasta -a skip -r NC_045512_2.fasta --skip-alignment -t 0.3 -m 500 -g 0.05
```
HIV-Trace creates the output.fasta and the .csv file but gets stuck in the last step when generating the JSON file. It does not throw an error, but just keeps running forever.

hivtrace.log:
```
DEBUG:root:Reference name set to XXXX
INFO:root:{"type": "status update", "index": 3, "title": "Computing pairwise TN93 distances", "status": 2, "msg": ""}
DEBUG:root:tn93 -q -o XXX/tmp/hivtrace-q1bgq69g/SARS-Cov-10K-ALIGNED.fasta_user.tn93output.csv -t 0.3 -a skip -l 500 -g 1.0 -f csv SARS-Cov-10K-ALIGNED.fasta_output.fasta
INFO:root:{"type": "status update", "index": 3, "title": "Computing pairwise TN93 distances", "status": 3, "msg": ""}
INFO:root:{"type": "status update", "index": 4, "title": "Inferring, filtering, and analyzing molecular transmission network", "status": 2, "msg": ""}
DEBUG:root:XXX/.conda/envs/hivtrace/bin/hivnetworkcsv -i XXX/tmp/hivtrace-q1bgq69g/SARS-Cov-10K-ALIGNED.fasta_user.tn93output.csv -t 0.3 -f plain -j -o
```

**Comment by MacPanich** [comment]
I'm having the same issues. No JSON file generated after entering the command. Only output.fast and .csv are found. Any solutions yet?

**Comment by denisbeslic** [comment]
@MacPanich It finished successfully after ~8 hours.. 
I would recommend to lower the threshold parameter "-t", f.e. to 0.0001 or 0.00001, which reduced the runtime to 5-10 minutes for generating the JSON result file.

**Comment by MacPanich** [comment]
@denisbeslic Your method works. I was able to generate JSON result file now. Thank you so much.
