### ISSUE TITLE
Failed building wheel for bioext

### ISSUE THREAD

**Issue by arya-aa** [veg/hivtrace#82]
pip3 install hivtrace
When I use the above command to install hivtrace, I encounter the following error：

error: Command "x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.10 -c BioExt/rateclass/_rateclass.cpp -o build/temp.linux-x86_64-cpython-310/BioExt/rateclass/_rateclass.o -O3 -I." failed with exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bioext
  Running setup.py clean for bioext
Failed to build bioext
Installing collected packages: bioext
  Running setup.py install for bioext ... error
  error: subprocess-exited-with-error

  × Running setup.py install for bioext did not run successfully.
  │ exit code: 1
  ╰─> [549 lines of output]
 error: Command "x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.10 -c BioExt/rateclass/_rateclass.cpp -o build/temp.linux-x86_64-cpython-310/BioExt/rateclass/_rateclass.o -O3 -I." failed with exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> bioext

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

pip3 freeze
appdirs==1.4.4
asn1crypto==0.24.0
attrs==21.2.0
Automat==20.2.0
bcrypt==3.2.0
beautifulsoup4==4.10.0
beniget==0.4.1
biopython==1.81
blinker==1.4
Bottleneck==1.3.2
Brotli==1.0.9
certifi==2018.1.18
chardet==3.0.4
click==6.7
cloud-init==22.1
colorama==0.3.7
command-not-found==0.3
ConfigArgParse==1.5.3
configobj==5.0.6
constantly==15.1.0
cryptography==3.4.8
cycler==0.11.0
Cython==0.29.33
dbus-python==1.2.18
decorator==4.4.2
defusedxml==0.7.1
distro-info===1.1build1
et-xmlfile==1.0.1
fakemp==0.9.1
fonttools==4.29.1
fs==2.4.12
gast==0.5.2
hivclustering==1.6.3
hivtrace==0.6.2
hppy==0.9.9
html5lib==1.1
httplib2==0.9.2
hyperlink==17.3.1
hyphy-python==0.1.10
idna==2.6
importlib-metadata==4.6.4
incremental==21.3.0
iniconfig==1.1.1
jdcal==1.0
Jinja2==2.10
joblib==1.2.0
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
kiwisolver==1.3.2
language-selector==0.1
llvmlite==0.38.0
lxml==4.8.0
lz4==3.1.3+dfsg
MarkupSafe==2.0.1
matplotlib==3.5.1
more-itertools==8.10.0
mpmath==0.0.0
netifaces==0.11.0
networkx==2.4
nose==1.3.7
numba==0.55.1
numexpr==2.8.1
numpy==1.24.0
oauthlib==2.0.6
odfpy==1.4.2
olefile==0.46
openpyxl==3.0.9
packaging==21.3
PAM==0.4.2
pandas==1.3.5
pexpect==4.2.1
Pillow==9.0.1
pluggy==0.13.0
ply==3.11
psutil==5.9.0
py==1.10.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
Pygments==2.11.2
PyGObject==3.42.1
PyHamcrest==2.0.2
PyJWT==1.5.3
pyOpenSSL==17.5.0
pyparsing==2.4.7
pysam==0.20.0
pyserial==3.4
pytest==6.2.5
python-apt==2.4.0+ubuntu1
python-dateutil==2.8.1
python-debian==0.1.32
pythran==0.10.0
pytz==2022.1
PyYAML==5.4.1
requests==2.18.4
requests-unixsocket==0.1.5
scikit-learn==0.23.2
scipy==1.10.1
service-identity==18.1.0
simplejson==3.17.6
six==1.11.0
sos==4.3
soupsieve==2.3.1
ssh-import-id==5.7
sympy==1.9
systemd-python==234
tables==3.7.0
threadpoolctl==3.1.0
tn93==1.2.0
toml==0.10.2
tornado==6.2
Twisted==22.1.0
ubuntu-advantage-tools==8001
ufoLib2==0.13.1
ufw==0.36
unattended-upgrades==0.1
unicodedata2==14.0.0
urllib3==1.22
webencodings==0.5.1
xlwt==1.3.0
zipp==1.0.0
zope.interface==5.4.0

**Comment by stevenweaver** [comment]
Dear @arya-aa, 

Thank you. Yes, there is an outstanding issue with bioext and the latest versions of python. 

Until I have time to update bioext to be compatible, you can use python version 9 and the following versions. 

```
(env) 11:07:52 sweaver@Stevens-MacBook-Pro.local Programming pip freeze
bioext==0.20.3
biopython==1.79
Cython==0.29.23
fakemp==0.9.1
hppy==0.9.9
hyphy-python==0.1.10
joblib==1.0.1
numpy==1.20.3
pysam==0.19.1
scipy==1.8.1
six==1.16.0
tornado==6.2
```
Best,
Steven

**Comment by arya-aa** [comment]
> Dear @arya-aa,
> 
> Thank you. Yes, there is an outstanding issue with bioext and the latest versions of python.
> 
> Until I have time to update bioext to be compatible, you can use python version 9 and the following versions.
> 
> ```
> (env) 11:07:52 sweaver@Stevens-MacBook-Pro.local Programming pip freeze
> bioext==0.20.3
> biopython==1.79
> Cython==0.29.23
> fakemp==0.9.1
> hppy==0.9.9
> hyphy-python==0.1.10
> joblib==1.0.1
> numpy==1.20.3
> pysam==0.19.1
> scipy==1.8.1
> six==1.16.0
> tornado==6.2
> ```
> 
> Best, Steven

Thanks a lot!
