### ISSUE TITLE
hivtrace file input

### ISSUE THREAD

**Issue by ainursan210** [veg/hivtrace#83]
Dear Everyone,

I want to test our sequences through hivtrace. Now, I am not able to run it with my FASTA file.
Seems the hivtrace can not find my file. I tried different approaches - copied the exact path to file (from features of the file function), when it was stored on the Desktop, I moved the file to different folders, even to Python folder, where it was stored together with hivtrace file - still the hivtrace could not find my file. 
Could you please help me with this issue?
![Picture1](https://user-images.githubusercontent.com/130979569/232456212-96854682-caa7-4c29-aeef-635edfc92edf.jpg)

**Comment by spond** [comment]
Dear @ainursan210,

`./Users/polzovatel/Desktop/hiv.fasta` is an invalid file path. By putting `.` in front of the path, you are asking the system to look for it in the current directory. Delete `.` and try again. You can always check to see if the file exists by typing something like

```
(base) sergei@M1Max ~ % file /Users/sergei/Desktop/test.bf
/Users/sergei/Desktop/test.bf: ASCII text, with no line terminators
```

Best,
Sergei

**Comment by ainursan210** [comment]
> Dear @ainursan210,
> 
> `./Users/polzovatel/Desktop/hiv.fasta` is an invalid file path. By putting `.` in front of the path, you are asking the system to look for it in the current directory. Delete `.` and try again. You can always check to see if the file exists by typing something like
> 
> ```
> (base) sergei@M1Max ~ % file /Users/sergei/Desktop/test.bf
> /Users/sergei/Desktop/test.bf: ASCII text, with no line terminators
> ```
> 
> Best, Sergei

Dear Sergei,
Thank you so much for your help.
I tried to delete the dot from the command and I have got a traceback.
Could you please look at it?
It seems like the hivtrace was not installed properly...But when I type "hivtrace", it gives me a number of intructions.
![traceback](https://user-images.githubusercontent.com/130979569/232687974-0b7b8d50-1d4d-4bf2-ae37-52a2515f66bc.jpg)


Thank you!

**Comment by stevenweaver** [comment]
Dear @ainursan210, 

You need to install `tn93`. 

Directions to install from source are here -- https://github.com/veg/tn93. Alternatively, one can use `conda` to installed `tn93` as well. 

Best,
Steven

**Comment by ainursan210** [comment]
> an a

Dear Steven,

After enormous attempts of installing/removing hivtrace required programs (I had many issues with numpy), I think I was able to install it properly. (I wanted to use the hivtrace so bad that I bought new laptop lol)
However I still got tracebacks. What could it be?
I am new in this field, sorry for lots of questions from me.

Thank you!
<img width="1179" alt="Снимок экрана 2023-04-21 в 20 51 46" src="https://user-images.githubusercontent.com/130979569/233669001-84bd5e37-6f2a-4c5b-860a-9408eb2ef9b0.png">
