### ISSUE TITLE
clusters are not same?

### ISSUE THREAD

**Issue by liamxg** [veg/hivtrace#86]
<img width="1092" alt="image" src="https://github.com/veg/hivtrace/assets/46078579/37c81499-766e-46a6-8f4d-f097be5a12b8">

**Comment by spond** [comment]
Dear @liamxg,

The table count includes the singleton “cluster” ie all those nodes which are connected to nothing. I’ll mark that as a bug and keep the issue open. You can check the cluster count as well by tabbing over to the cluster table. 

Best,
Sergei
