### ISSUE TITLE
how to load the metadata?

### ISSUE THREAD

**Issue by liamxg** [veg/hivtrace#87]
<img width="294" alt="image" src="https://github.com/veg/hivtrace/assets/46078579/163b2e41-ec19-4d91-a8b5-51f350d9d6a5">

**Comment by stevenweaver** [comment]
Dear @liamxg, 

Please use https://hivtrace.datamonkey.org to visualize your results. You can use the `json` output from the `hivtrace` command. 

Best,
Steven
