### ISSUE TITLE
how to define the threshold?

### ISSUE THREAD

**Issue by liamxg** [veg/hivtrace#88]
@stevenweaver @spond

**Comment by stevenweaver** [comment]
We have a new manuscript in the works for this very thing. Please stay tuned!

**Comment by stevenweaver** [comment]
It's undergoing some final revisions. It is a bit different.

**Comment by spond** [comment]
Dear @liamxg,

If you use `hivnetworkcsv` (a part of https://github.com/veg/hivclustering), which is a component of `HIV-TRACE`, you can use `--threshold auto` option. 

For example, using the data which ships with `hivclustering`

```
$hivnetworkcsv -i examples/tn93-0.03.csv -f plain -t auto
....
ERROR : Could not automatically determine a distance threshold; no sufficiently strong outlier, best guess 0.01726 (score 1.07156)
```

In this particular case, the tool is suggesting the threshold of `0.01726`, even though it's not confident enough to just use it (it will be in other cases, as the upcoming manuscript will detail). 

So next, you could use

```
$hivnetworkcsv -i examples/tn93-0.03.csv -f plain -t 0.01726
```

Cheers,
Sergei
